steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/thor-218109/hello-app:$BUILD_ID', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/thor-218109/hello-app:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/hello-web', 'gcr.io/thor-218109/hello-app:$BUILD_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-web-cluster'
images: ['gcr.io/thor-218109/hello-app:$BUILD_ID']