steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/thor-218109/github-ugetragul-gke_testing:latest', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/thor-218109/github-ugetragul-gke_testing:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/github-ugetragul-gke_testing', 'gcr.io/thor-218109/github-ugetragul-gke_testing:latest']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-world-cluster'
images: ['gcr.io/thor-218109/github-ugetragul-gke_testing:latest']