steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: gcloud container clusters get-credentials hello-web-cluster --zone=us-central1-a
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/thor-218109/hello-app:1.0.$REVISION_ID', '.']
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/thor-218109/hello-app:1.0.$REVISION_ID']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/hello-web', 'hello-app=gcr.io/thor-218109/hello-app:1.0.$REVISION_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-web-cluster'
